dist: trusty
language: clojure
script:
  - make check
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
  #- openjdk8
#addons:
#  apt:
#    sources:
#      -
notifications:
  email:
      - oubiwann@gmail.com
